POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Vedant",
    "email": "vedantishere@gmail.com",
    "password": "123456"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "name": "Vedant",
    "email": "vedantishere@gmail.com",
    "password": "123456"
}

###

GET http://localhost:5000/api/protected
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NTMzNDUyNSwiZXhwIjoxNzU1MzM4MTI1fQ.LEUp8rsfkiCThUVD2l7w72zeubFDfCnlIhwUoE7X_xU

###

GET http://localhost:5000/api/user/profile
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NTMzNjY1NywiZXhwIjoxNzU1MzQwMjU3fQ.UfyfIADRa-YIMV0BYhrOwS0vY066LWIf1aALGxPoIpk
###

POST http://localhost:5000/api/movies 
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NTUzNTc0NSwiZXhwIjoxNzU1NTM5MzQ1fQ.Tkwuxc1JgTTbS9AtQTOhmkT7L5jn9vEEN6o2i7cyOSs
{
  "title": "Pushpa",
  "genre": "Action, Thriller",
  "duration": 148,
  "status": "planned",
  "rating": 8.1,
  "posterPath": null,
  "tmdbId": "1234",
  "contentType": "movie"
}

###

GET http://localhost:5000/api/movies
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NjE5NjYzNCwiZXhwIjoxNzU2MjAwMjM0fQ.UhhrY0KYXmetk7lZFHbHNOnXR831_82_NENWu5BbMmk

### 

DELETE http://localhost:5000/api/movies/689320f8ffd5feda2493cd2b
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NTQ0NTQ1OCwiZXhwIjoxNzU1NDQ5MDU4fQ.Q0dmwsF3ZUuiLFI8t1vO4wRniFefa7cEdV_EWKC0H6w

###

PUT http://localhost:5000/api/movies/6890677838d4ca8474adac1d
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NTUxMTc2MCwiZXhwIjoxNzU1NTE1MzYwfQ.ba5ark7m9vMRRP0LD3or7jaN8KGlsmmpp7qzmfYM5cE
Content-Type: application/json

{
    "contentType": "movie"
}

###

GET http://localhost:5000/api/movies/stats?contentType=tv
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg4Y2YyYjJjM2IwNGMxMDk5OTM1NDE0In0sImlhdCI6MTc1NjE0MDMwMCwiZXhwIjoxNzU2MTQzOTAwfQ.e8WVKJz0k6RMxxWEZM9fr98wK6poK5u258UT56vbd6Q